version: '3.8'
services:
  backend:
    container_name: backend_container
    restart: always
    pull_policy: build
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      - app  
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=demonstrator
      - MONGO_HOST=mongodb_container
      - MONGO_DATABASE=chatgpt
    env_file:
      - ./server/.env
    depends_on:
      - mongodb
      - mysqldb

  frontend:
    container_name: frontend_container
    restart: always
    pull_policy: build
    environment:
      - REACT_BACKEND_API_URL=http://backend:4000
    networks:
      - app
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - ./client/.env
    depends_on:
      - backend

  mysqldb:
    container_name: mysqldb_container
    image: mysql:8.0
    restart: always
    networks:
      - app
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demonstrator
      MYSQL_SQL_MODE: "NO_ENGINE_SUBSTITUTION"
    command: --sql-mode="NO_ENGINE_SUBSTITUTION"

  nginx:
    container_name: nginx_container
    pull_policy: build
    build:
      context: ./nginx
    networks:
      - app
    ports:
      - "80:80"
    depends_on:
      - mongodb
      - mysqldb
      - backend
      - frontend
  mongodb:
    container_name: mongodb_container
    image: mongo:jammy
    restart: always
    networks:
      - app
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:


networks:
  app:
    driver: bridge
