version: '3.8'
services:

  backend:
    container_name: backend_container
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5555:5555
    networks:
      - app
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=dbpassword
      - MYSQL_DATABASE=demonstrator
    env_file:
      - ./server/.env
    depends_on:
      - mongodb
      - mysqldb

  frontend:
    container_name: frontend_container
    restart: always
    environment:
      - REACT_APP_BACKEND=http://localhost:5555
    ports:
      - 5050:80
    networks:
      - app
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - ./client/.env
    depends_on:
      - backend

  mysqldb:
    container_name: mysqldb_container
    image: mysql:8.0
    restart: always
    networks:
      - app
    env_file: ./server/.env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demonstrator
    ports:
      - 3307:3306

  nginx:
    container_name: nginx_container
    build:
      context: ./nginx
    networks:
      - app
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

  mongodb:
    container_name: mongodb_container
    image: mongo:jammy
    restart: always
    networks:
      - app
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:


networks:
  app:
    driver: bridge
